---
# main.yml for nerve4-managed-kubernetes

- name: Check if the /etc/modprobe.d/blacklist-ipv6.conf exists
  stat:
    path: "/etc/modules-load.d/containerd.conf"
  register: containerd_check

- include_tasks: setup-users.yml

- include_tasks: rhel-install-k8s.yml
  when: 
    containerd_check.stat.exists == False and
    (ansible_distribution == "CentOS") or
    (ansible_distribution == "RedHat") or
    (ansible_distribution in "Rocky")

- include_tasks: ubuntu-install-k8s.yml
  when:
    - containerd_check.stat.exists == False
    - ansible_distribution == "Ubuntu"

- include_tasks: setup-base-cni.yml

- include_tasks: setup-k8s-master.yml
  when: masters_var is defined and masters_var

- include_tasks: setup-k8s-workers.yml
  when: workers_var is defined and workers_var