---
# rhel-install-k8s.yml for nerve4-managed-kubernetes

- name: Install and configure dependencies on Rhel 7.x
  ansible.builtin.yum:
    name: "{{ rhel7_pkgs }}"
    state: present
  when:
    - ansible_distribution_major_version == "7"

- name: Install and configure dependencies on Rhel 8.x / Rocky Linux
  ansible.builtin.dnf:
    name: "{{ rhel8_pkgs }}"
    state: present
  when:
    (ansible_distribution_major_version == "8") or
    (ansible_distribution in "Rocky")

- name: Create containerd config file
  ansible.builtin.file:
    path: "/etc/modules-load.d/containerd.conf"
    state: touch

- name: Setup containerd config file
  ansible.builtin.blockinfile:
    path: "/etc/modules-load.d/containerd.conf"
    block: |
      overlay
      br_netfilter

- name: Run modprobe
  become: true
  ansible.builtin.shell: |
    sudo modprobe overlay
    sudo modprobe br_netfilter

- name: Set system configurations for Kubernetes networking
  ansible.builtin.file:
    path: "/etc/sysctl.d/kubernetes.conf"
    state: "touch"

- name: Setup Kubernetes networking config
  ansible.builtin.blockinfile:
    path: "/etc/sysctl.d/kubernetes.conf"
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1

- name: Apply new settings
  become: true
  ansible.builtin.command: 
    cmd: sysctl --system

- name: Add docker repository
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Update YUM
  become: true
  ansible.builtin.command: 
    cmd: yum update -y
  when:
    - ansible_distribution_major_version == "7"

- name: Install containerd
  become: true
  ansible.builtin.yum:
    name: "containerd.io"
    state: latest
  when:
    - ansible_distribution_major_version == "7"

- name: Update DNF
  become: true
  ansible.builtin.command: 
    cmd: dnf update -y
  when:
    (ansible_distribution_major_version == "8") or
    (ansible_distribution in "Rocky")

- name: Install containerd
  become: true
  ansible.builtin.dnf:
    name: "containerd.io"
    state: latest
  when:
    (ansible_distribution_major_version == "8") or
    (ansible_distribution in "Rocky")

- name: Configure containerd
  become: true
  ansible.builtin.shell: |
    sudo mkdir -p /etc/containerd
    sudo containerd config default | sudo tee /etc/containerd/config.toml

- name: Enable containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: Disable swap
  become: true
  ansible.builtin.shell: |
    sudo swapoff -a -v
    sudo cp /etc/fstab /etc/fstab.bak
    sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Add kubernetes repository
  ansible.builtin.yum_repository:
    name: kubernetes
    description: kubernetes YUM repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: true
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install kubernetes packages
  become: true
  ansible.builtin.yum:
    name: "{{ kubernetes_rhel7_pkgs }}"
    state: present
  when:
    - ansible_distribution_major_version == "7"

- name: Install kubernetes packages
  become: true
  ansible.builtin.dnf:
    name: "{{ kubernetes_rhel7_pkgs }}"
    state: present
  when:
    (ansible_distribution_major_version == "8") or
    (ansible_distribution in "Rocky")