---
# setup-k8s-workers.yml for nerve4-managed-kubernetes

- name: Copy join command from Ansiblehost to the worker nodes
  become: yes
  ansible.builtin.copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: 0777

- name: Join the Worker nodes to the cluster
  become: yes
  ansible.builtin.command: 
    cmd: sh /tmp/kubernetes_join_command
  register: joined_or_not