---
# setup-k8s-master.yml for nerve4-managed-kubernetes

- name: Initialize the cluster
  become: yes
  become_user: "{{ k8s_admin_user }}"
  ansible.builtin.shell: |
    sudo kubeadm init --pod-network-cidr={{ k8s_pod_network }} --kubernetes-version "{{ kubernetes_ver }}"
  args:
    chdir: $HOME

- name: Create .kube directory
  become: yes
  become_user: "{{ k8s_admin_user }}"
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copies admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ k8s_admin_user }}/.kube/config"
    remote_src: yes

- name: Setup kube config ownership
  become: yes
  become_user: "{{ k8s_admin_user }}"
  ansible.builtin.shell: |
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Pause for "{{ k8s_controlplane_timoe }}" seconds to Controlplain
  ansible.builtin.pause:
    seconds: "{{ k8s_controlplane_timoe }}"

- name: Get the token for joining the worker nodes
  become: yes
  become_user: "{{ k8s_admin_user }}"
  ansible.builtin.shell: |
    kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: Debug
  ansible.builtin.debug:
    msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file
  become: yes
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777